version: '3.8'

services:
  dbmysql:
    container_name: psmysql
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps
    ports:
      - "3308:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pps"]
      timeout: 20s
      retries: 10
    networks:
      default:
        ipv4_address: 172.18.0.2

  pspresta:
    container_name: psweb
    image: prestashop/prestashop:1.7.7.7
    volumes:
      - prestadata:/var/www/html
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "8088:80"
    environment:
      PS_INSTALL_AUTO: 1
      DB_SERVER: dbmysql
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.3

volumes:
  mysqldata:
  prestadata:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
